### ISSUE TITLE
Typos in the README.md

### ISSUE THREAD

**Issue by olegchursin** [learn-co-curriculum/introduction-to-the-dom#21]
# 1
## Lesson: Introduction to the DOM
**Section title: TELL IT TO ME IN BULLET POINTS**
**Sentence**: But as we just saw by deleting the header of the page, what is displayed can change.
**Needed change**: ‘header’ needs to be replaced by ‘body'
**Explanation**: We have just deleted ‘body’ element in the practice example before, not ‘header’.

# 2
## Lesson: Introduction to the DOM
**Section title: THIS IS STILL ABOUT JAVASCRIPT, RIGHT?**
**Exact position**: Example image right under the phrase "This will return something like this:”
**Needed change**: replace the code snippet to display <body>...</body>

Further down the lesson *header* and *body* sections are used interchangeably which may be misleading for the target audience (i.e. aspiring developers).

**Comment by jmburges** [comment]
Thanks @olegchursin we fixed the issues :)
