### ISSUE TITLE
Screen capture replay is WAY too fast

### ISSUE THREAD

**Issue by digitaltara** [learn-co-curriculum/introduction-to-the-dom#27]
In the Intro to The DOM section, item 1. Open the Console, the gif replay of how to open the console is really fast. Since it plays on repeat, it has almost a strobe effect and is horrible to look at. 

I'm on macOS 10.12.6, Chrome Version 63.0.3239.84.

![opentheconsole_gif](https://user-images.githubusercontent.com/10995708/34755864-e94eb5c6-f57b-11e7-8440-e2aa9c482aea.png)

**Comment by FernanGonzalez** [comment]
I agree. It's the same on Firefox on Windows 10.

**Comment by joshuabamboo** [comment]
Here is a slowed down version of the gif in the meantime until this is fixed https://imgur.com/a/pRjWF

**Comment by maxwellbenton** [comment]
Thank you for providing feedback, @digitaltara.

We have updated this lesson's readme, no longer use this GIF, and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
