### ISSUE TITLE
Chrome menu bar not available

### ISSUE THREAD

**Issue by FernanGonzalez** [learn-co-curriculum/introduction-to-the-dom#28]
The lesson says:

> From this webpage, look at the Chrome menubar at the top of the page. Click on "View", then select "Developer", then "Developer Tools". This will open the Google Developer Console.

While I can inspect the website, I can't find the Chrome menu bar. I'm on Windows 10.

![2018-01-12](https://user-images.githubusercontent.com/33208622/34858881-22afd66e-f753-11e7-85a5-adcda154b72d.png)

Best regards.

**Comment by maxwellbenton** [comment]
Thank you for providing feedback, @FernanGonzalez.

We have updated this lesson's readme and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
