### ISSUE TITLE
typos/grammar needs to be proofread

### ISSUE THREAD

**Issue by louisraymond** [learn-co-curriculum/introduction-to-the-dom#30]

**Comment by maxwellbenton** [comment]
Thank you for providing feedback, @louisraymond.

We have updated this lesson's readme and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙

**Comment by louisraymond** [comment]
the irony of my own typo is not lost on me
