### ISSUE TITLE
Opening Developer Tools instruction no longer correct in Intro to DOM

### ISSUE THREAD

**Issue by chai-ito** [learn-co-curriculum/introduction-to-the-dom#31]
One of Chrome's recent(ish) updates changed how to open the Developer Tools console. Currently the instructions in Introduction to the DOM read like so

> From this web page, look at the Chrome menubar at the top of the page. Click on "View", then select "Developer", then "Developer Tools". This will open the Google Developer Console.

They should read

> From this web page, look at the Chrome menubar at the top of the page. Click on "More tools", then "Developer Tools". This will open the Google Developer Console.

(Apologies if this isn't the correct place to report this, I've just started Bootcamp Prep and am in personally uncharted waters)

**Comment by maxwellbenton** [comment]
Hi @chai-ito,

Thank you for submiting this issue!  We've updated this lesson to include the updated instructions.

Thank you for contributing!
